# Generated by Django 5.2.1 on 2025-05-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='exames',
            field=models.TextField(default='Sem exames'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='medicamentos_continuos',
            field=models.TextField(default='Sem medicamentos continuos'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='numeroProntuario',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='prescricao_medica',
            field=models.TextField(default='Sem prescição médica'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='queixas_principais',
            field=models.TextField(default='Sem queixas principais'),
        ),
    ]
